# Generated by Django 5.0.4 on 2024-04-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название бренда')),
                ('description', models.TextField(blank=True, verbose_name='Описании бренда')),
                ('photo', models.ImageField(blank=True, upload_to='images/brand', verbose_name='Лого бренда')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описании категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(max_length=100, verbose_name='Фамилия клиента')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество клиента')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('MG', 'Самовывоз'), ('CR', 'Курьер'), ('PP', 'Точка выдачи заказов')], default='MG', max_length=2, verbose_name='Тип доставки')),
                ('commentary', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заказа')),
                ('datetime_finish', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'permissions': [('change_delivery_type', 'Возможность изменить тип доставки'), ('can_finish_order', 'Возможность завершить заказ')],
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поставщика')),
                ('agent_firstname', models.CharField(max_length=100, verbose_name='Фамилия агента')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Имя агента')),
                ('patronymic_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество агента')),
                ('agent_telephone', models.CharField(max_length=100, verbose_name='Телефон представителя')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес компании')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Pos_parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение характеристики')),
                ('parametr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.parametr', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Позиция характеристики',
                'verbose_name_plural': 'Позиции характеристики',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='Pos_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во товара')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.supply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставки',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Цена')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение')),
                ('is_exist', models.BooleanField(default=True, verbose_name='Существует?')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.category', verbose_name='Категория')),
                ('parametr', models.ManyToManyField(through='musicshop.Pos_parametr', to='musicshop.parametr', verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Музыкальный инструмент',
                'verbose_name_plural': 'Музыкальный инструмент',
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='product',
            field=models.ManyToManyField(through='musicshop.Pos_supply', to='musicshop.tool', verbose_name='Строительный инструмент'),
        ),
        migrations.AddField(
            model_name='pos_supply',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.tool', verbose_name='Строительный инструмент'),
        ),
        migrations.AddField(
            model_name='pos_parametr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.tool', verbose_name='Строительный инструмент'),
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во')),
                ('discount', models.IntegerField(verbose_name='Скидка на позицию')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicshop.tool', verbose_name='Строительный инструмента')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='musicshop.Pos_order', to='musicshop.tool', verbose_name='Строительный инструмент'),
        ),
    ]
