# Generated by Django 5.0.4 on 2024-04-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Строительный инструмент', 'verbose_name_plural': 'Строительный инструмент'},
        ),
    ]
